version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo
    env_file:
      - ./server/config.env
    volumes:
      - ./server:/app
    networks:
      - hesnetwork

  client:
    build: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
    env_file:
      - ./client/.env
    networks:
      - hesnetwork

  mongo:
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo-data:/data/db
    networks:
      - hesnetwork

volumes:
  mongo-data:

networks:
  hesnetwork:
    driver: bridge